### ISSUE TITLE
Enhacement: tags

### ISSUE THREAD

**Issue by ecentinela** [schmittjoh/JMSJobQueueBundle#22]
Allow to tag a job with multiple tags and allow to include / exclude tags on the command.
So, for example, I can run a command with video_conversion tag (a long running task) and another command with email_sending tag (a quick and important task).

**Comment by sadortun** [comment]
You can use multiples queues for that, and limiit the number of concurent jobs
```yaml
    queue_options:
        video_conversion:
            max_concurrent_jobs: 2 
```

http://jmsyst.com/bundles/JMSJobQueueBundle/master/usage#fine-grained-concurrency-control-through-queues
